### ISSUE TITLE
[功能建议]希望文档能在详细一些

### ISSUE THREAD

**Issue by Eisaichen** [lqzhgood/Shmily-Get-QQ-PC_MHT#3]
node安装教程中给出的下载地址[https://nodejs.org/dist/](https://nodejs.org/dist/)提供的是exe文件，除了页面排版不利于新手之外，还不包含必须的npm
不如直接官网下载[https://nodejs.org/en/download](https://nodejs.org/en/download)

第3步） 修改config.js，感觉是个很重要的步骤，但一笔带过了，完全不知道要修改什么
              文件内的注释语法也很奇怪，需要很强的..悟性。希望Readme中能直接给出示例

第4步 `npm run build`，之前还需`npm i`安装依赖

**Comment by Eisaichen** [comment]
Dockerfile
```
FROM node

ENV NODE_OPTIONS="--max-old-space-size=8192"
VOLUME /app

RUN apt update && \
    apt install php-cgi git -y && \
    apt install php -y -y && \
    git clone https://github.com/lqzhgood/Shmily-Get-QQ-PC_MHT /res && \
    cd /res && \
    npm i && \
    apt clean

WORKDIR /app
ENTRYPOINT cp -ru /res/* /app && npm run build
```
主机上`mkdir -p ./app/input`
把.mht文件扔进./app/input就行了


docker compose
```
version: "3.8"

services:
  shmily:
    container_name: shmily
    build:
      context: .
    restart: "no"
    volumes:
      - "./app:/app"
```
